<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MessagePack" />
		<PackageReference Include="System.Runtime.InteropServices" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\illusion.Common\illusion.Common.csproj" />
	</ItemGroup>
	
	<Target Name="CopyNativeDll" AfterTargets="Build">
		<ItemGroup><NativeDllFiles Include="$(CppBuildDir)bin\$(CppConfiguration)\*" /></ItemGroup>
		<Copy SourceFiles="@(NativeDllFiles)" DestinationFolder="$(OutputPath)" OverwriteReadOnlyFiles="true" SkipUnchangedFiles="true" />
	</Target>

</Project>
