using System.Text;
using illusion.Common.Types;
using illusion.CoreLogic.Prover;

namespace illusion.Generator;

/// <summary>
/// Minimal constructive prover that emits code only from a successful analytical
/// proof trace. It refuses to generate unverifiable content.
/// </summary>
public sealed class DeterministicConstructiveProver : IConstructiveProver
{
    private readonly IAnalyticalProver _analyticalProver;

    public DeterministicConstructiveProver(IAnalyticalProver analyticalProver)
    {
        _analyticalProver = analyticalProver ?? throw new IAException<ArgumentNullException>(nameof(analyticalProver));
    }

    public string GenerateCode(Expression proposition, string targetLanguage = "C#")
    {
        if (!StringComparer.OrdinalIgnoreCase.Equals(targetLanguage, "C#"))
            throw new IAException<NotSupportedException>($"target language '{targetLanguage}' is not supported");

        var proof = _analyticalProver.Prove(proposition);
        if (!proof.IsSuccess)
            throw new IAException<InvalidOperationException>(proof.ErrorMessage ?? "proposition is not provable");

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated by Illusionary-AI deterministic constructive prover.");
        builder.AppendLine($"// Trace: {proof.TraceId}");
        foreach (var step in proof.Steps)
            builder.AppendLine($"// Step {step.StepNumber}: {step.RuleName} => {step.StepExpression.ToCanonicalString()}");
        builder.AppendLine("public static class GeneratedProofArtifact");
        builder.AppendLine("{");
        builder.AppendLine("    public static bool Verify() => true;");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
